# Generated by Django 5.2.4 on 2025-07-12 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zone', models.IntegerField()),
                ('bidders', models.JSONField(default=dict)),
                ('current_price', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('millet', 'Millet'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], max_length=20)),
                ('zone', models.IntegerField()),
            ],
        ),
    ]
