# Generated by Django 5.2.4 on 2025-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_stagingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
