# Generated by Django 5.2.3 on 2025-06-25 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transporter_id', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('total_capacity', models.IntegerField()),
                ('price_per_kg', models.FloatField()),
                ('price_per_km', models.FloatField()),
                ('support_loading', models.BooleanField(default=False)),
                ('support_unloading', models.BooleanField(default=False)),
                ('start_place', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('destination_place', models.CharField(max_length=100)),
                ('destination_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop', models.IntegerField()),
                ('to_stop', models.IntegerField()),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('available_capacity', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transport.transportschedule')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('to_place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('approx_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='transport.transportschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('farmer_id', models.CharField(max_length=100)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transportschedule')),
            ],
        ),
    ]
