# Generated by Django 5.2.3 on 2025-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='desscription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
