# Generated by Django 5.2.3 on 2025-07-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_booking_desscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='desscription',
            new_name='description',
        ),
    ]
