# Generated by Django 5.2.3 on 2025-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_rename_desscription_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
