# Generated by Django 5.2.3 on 2025-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
